language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

sudo: false

addons:
  apt:
    packages:
      - python-numpy

install:
  - pip install -r requirements_dev.txt
  - pip install steno3d_obj
  - pip install steno3d_stl

  - git clone http://github.com/3ptscience/steno3d-obj.git
  - git clone http://github.com/3ptscience/steno3d-stl.git

script:
  - make tests
  - nosetests steno3d-obj/
  - nosetests steno3d-stl/
  - if ! [ $TRAVIS_PYTHON_VERSION == "3.3" ]; then
      make test-docs;
    fi

after_success:
  - openssl aes-256-cbc -K $encrypted_f8d68abb14d0_key -iv $encrypted_f8d68abb14d0_iv -in .pypirc.enc -out ~/.pypirc -d
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" -a $TRAVIS_PYTHON_VERSION == "2.7" -a -n "$(grep version setup.py | cut -d \' -f 2 | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$')" ]; then
      make publish;
    fi
  - if [ "$TRAVIS_BRANCH" = "beta" -a "$TRAVIS_PULL_REQUEST" = "false" -a $TRAVIS_PYTHON_VERSION == "2.7" -a -n "$(grep version setup.py | cut -d \' -f 2 | grep -E '^[0-9]+\.[0-9]+\.[0-9]+b[0-9]+$')" ]; then
      make publish;
    fi

notifications:
 slack: 3point:n4uGopqXrpbYFbslpV5z0tyO
 email: false
